export const TEMPLATES = {
  classico: {
    id: "classico",
    nome: "Clássico ABNT",
    descricao: "Times New Roman 12pt • Tradicional",
    preview: "serif",
    fonte: "Times-Roman",
    fonteBold: "Times-Bold",
    fonteItalic: "Times-Italic",
    tamanhoCorpo: 12,
    tamanhoTitulo: 14,
    espacoEntreLinhas: 1.5,
    corTitulo: { r: 0, g: 0, b: 0 },
    corTexto: { r: 0, g: 0, b: 0 },
    corDestaque: { r: 0.8, g: 0.2, b: 0.0 },
    recuoParagrafo: 35,
  },
  moderno: {
    id: "moderno",
    nome: "Moderno Clean",
    descricao: "Helvetica 12pt • Limpo e atual",
    preview: "sans-serif",
    fonte: "Helvetica",
    fonteBold: "Helvetica-Bold",
    fonteItalic: "Helvetica-Oblique",
    tamanhoCorpo: 12,
    tamanhoTitulo: 14,
    espacoEntreLinhas: 1.5,
    corTitulo: { r: 0.13, g: 0.13, b: 0.13 },
    corTexto: { r: 0.2, g: 0.2, b: 0.2 },
    corDestaque: { r: 1, g: 0.3, b: 0 },
    recuoParagrafo: 35,
  },
  vermelho: {
    id: "vermelho",
    nome: "Destaque Vermelho",
    descricao: "Helvetica 12pt • Títulos em vermelho",
    preview: "sans-serif",
    fonte: "Helvetica",
    fonteBold: "Helvetica-Bold",
    fonteItalic: "Helvetica-Oblique",
    tamanhoCorpo: 12,
    tamanhoTitulo: 14,
    espacoEntreLinhas: 1.5,
    corTitulo: { r: 0.75, g: 0.05, b: 0.05 },
    corTexto: { r: 0.15, g: 0.15, b: 0.15 },
    corDestaque: { r: 0.75, g: 0.05, b: 0.05 },
    recuoParagrafo: 35,
  },
  azul: {
    id: "azul",
    nome: "Corporativo Azul",
    descricao: "Helvetica 12pt • Títulos em azul",
    preview: "sans-serif",
    fonte: "Helvetica",
    fonteBold: "Helvetica-Bold",
    fonteItalic: "Helvetica-Oblique",
    tamanhoCorpo: 12,
    tamanhoTitulo: 14,
    espacoEntreLinhas: 1.5,
    corTitulo: { r: 0.1, g: 0.2, b: 0.7 },
    corTexto: { r: 0.15, g: 0.15, b: 0.15 },
    corDestaque: { r: 0.1, g: 0.2, b: 0.7 },
    recuoParagrafo: 35,
  },
  minimalista: {
    id: "minimalista",
    nome: "Minimalista",
    descricao: "Helvetica 11pt • Espaçado e elegante",
    preview: "sans-serif",
    fonte: "Helvetica",
    fonteBold: "Helvetica-Bold",
    fonteItalic: "Helvetica-Oblique",
    tamanhoCorpo: 11,
    tamanhoTitulo: 13,
    espacoEntreLinhas: 1.8,
    corTitulo: { r: 0, g: 0, b: 0 },
    corTexto: { r: 0.25, g: 0.25, b: 0.25 },
    corDestaque: { r: 0, g: 0, b: 0 },
    recuoParagrafo: 0,
  },
} as const;

export type TemplateId = keyof typeof TEMPLATES;
export type Template = (typeof TEMPLATES)[TemplateId];

export const getTemplate = (id: TemplateId): Template => TEMPLATES[id] ?? TEMPLATES.classico;
